# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa49dd88e02fec3c158d6e251ed6c002acc21f25d7130895dafd8e9fd4679fef3480ce8d5f6d87e0ed7a5ca72ea668069b30b63301cf2390b3c241943dc3f861

test:
  secret_key_base: a2930b2ded7b82bc5287bf7d45856e97aacf255d4e2d42aa2e2a8d85078972fd027d6e31284e00b667c16ab054b2a4d85581de2cec532a65180477af83b9c210

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
